### ISSUE TITLE
遭遇材料の取得（アプリ使用状況）

### ISSUE THREAD

**Issue by tauto1127** [BATTARI-team/BATTARI#8]

**Comment by tauto1127** [comment]
このようなusagestatsを使ってデータを取得し，以下のようなデータ構造にする
`
{
appName: "アプリ名が入る",
usageTime: 5
}`
usageTimeにはアプリの使用時間を分単位で入れてください(int型で)

**Comment by Ruri-Kinoshita** [comment]
頑張るやで．．．．．．．．．．．．．．．．．．．．．．
